#!/bin/bash

export VAULT_ADDR='https://vault.moveaws.com'

if [ -z $1 ]; then
  echo "Please provide secret key name"
  exit 1
fi

if [ -z $2 ]; then
  echo "Please provide path to file containing secret value"
  exit 1
fi

VALUE=`cat $2`

vault write --address="$VAULT_BASE_URL" $1 value="$VALUE"
