#!/bin/bash

export VAULT_ADDR='https://vault.moveaws.com'

if [ -z "$1" ]; then 
  echo "Plese provide key as a param in form  secret/project/keyname"
  exit 1
fi
echo vault read -address=$VAULT_ADDR $1
vault read -address=$VAULT_ADDR $1
