#!/bin/bash

export VAULT_ADDR='https://vault.moveaws.com'

if [ -z $1 ]; then 
 echo "Please provide policy name"
 exit 1
fi

echo vault token-create -address=$VAULT_ADDR -policy="$1" 
vault token-create -address=$VAULT_ADDR -policy="$1" 
